backend:
  name: github
  repo: ademca570/website-sdn-01-demangan
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Halaman Website"
    files:
      - file: "index.html"
        label: "Halaman Utama"
        name: "index"
        fields:
          - {label: "Judul Utama", name: "title", widget: "string"}
          - {label: "Isi Konten", name: "body", widget: "markdown"}
